version: "3.7"

services:
  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/code
  php72:
    build: "."
    container_name: "php72"
    volumes:
      - ./code:/code