version: "3.7"

services:
  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./code:/code
      - /etc/letsencrypt:/etc/nginx/ssl
  php73:
    build: "."
    container_name: "php73"
    volumes:
      - ./code:/code